server:
  port: 8100
spring:
  application:
    name: livelife-serve-register

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
  server:
    enable-self-preservation: false
